export default {
  id: 'chapter-06',
  number: '06',
  label: '기능 흐름',
  title: '핵심 기능의 전체 흐름',
  summary: '여러 화면에 걸친 작업을 시작부터 끝까지 설명합니다.',
  topics: [
    '공지 작성 → 발송 → 확인 → 재알림',
    '출석 세션 생성 → 참여 → 판정 → 운영진 확인',
    '스터디 운영 → 과제·제출 관리',
    '커뮤니티 스레드 생성 → 참여 → 관리',
    '프로젝트 지원 → 심사',
    '명함 생성 → 교환 → 보관',
  ],
  details: [
    {
      body: '운영진이 대상과 알림 여부를 지정해 공지를 발행하면, 수신자는 상세 진입 시 읽음으로 기록된다. 작성 권한자는 열람 현황에서 미확인자를 골라 다시 알릴 수 있다.',
      points: [
        '1. 공지 탭에서 운영진 공지 화면으로 들어가며, 현재 역할과 선택 탭에 쓰기 권한이 있을 때만 작성 버튼을 표시한다.',
        '2. 편집기에서 제목·본문·대상 기수를 채우고 선택적으로 이미지·링크·투표와 알림 발송 여부를 설정한다. 필수값이 없거나 수정 내용이 없으면 제출을 막는다.',
        '3. 생성은 이미지 업로드, 공지 생성, 선택적 투표 첨부 순서다. 실패 시 생성 상태를 오류로 바꾸고 알림을 띄운다. 투표 첨부에서 실패하면 공지 본체는 이미 생성됐을 수 있다.',
        '4. 수신자가 목록 또는 홈에서 상세를 열면 읽음 API를 한 번 호출한다. 읽음 실패만으로 상세 열람을 중단하지 않고, 성공하면 로컬 읽음 상태도 저장한다.',
        '5. 작성 권한자는 상세의 열람 현황에서 확인/미확인자를 구분하고 개인 스와이프 또는 미확인자 전체 재알림을 보낸다. 전체 발송은 페이지를 순회해 대상 ID를 모은다.',
      ],
      questions: ['발행 즉시 푸시를 보내지 않은 공지에도 재알림을 허용하는가?', '투표 첨부 실패로 공지만 생성된 경우의 운영 복구 절차는 무엇인가?', '미확인 판정 기준과 재알림 빈도 제한, 중복 발송 방지 정책을 확정해야 한다.'],
      sources: ['UMCApp/Features/Notice/Presentation/Sources/Views/StaffNotice/StaffNoticeView.swift:227', 'UMCApp/Features/Notice/Presentation/Sources/ViewModels/NoticeEditor/NoticeEditorViewModel.swift:242', 'UMCApp/Features/Notice/Presentation/Sources/ViewModels/NoticeEditor/NoticeEditorViewModel+Submit.swift:32', 'UMCApp/Features/Notice/Presentation/Sources/ViewModels/NoticeDetail/NoticeDetailViewModel+NoticeActions.swift:260', 'UMCApp/Features/Notice/Presentation/Sources/ViewModels/NoticeDetail/NoticeDetailViewModel+NoticeActions.swift:413'],
    },
    {
      body: '운영진이 출석 정책이 붙은 일정을 등록하면 챌린저에게 세션이 나타난다. 챌린저의 GPS 요청이나 사유 제출 결과는 운영진의 참여자별 판정 화면으로 이어진다.',
      points: [
        '1. 일정 등록 화면에서 제목·시간·장소·참여자·출석 정책의 시작/정시 마감/지각 마감을 정한다. 스터디 일정은 그룹과 주차 커리큘럼을 골라 등록한다.',
        '2. 제출 가능 조건과 권한·참여자 조회가 충족되어야 등록 CTA가 활성화된다. 스터디 일정은 일정 생성 뒤 그룹/주차 연결을 수행하는 2단계 작업이며 연결 실패 시 재시도/취소 분기를 둔다.',
        '3. 챌린저는 활동 탭의 출석 세션 또는 출석 딥링크로 도착한다. 사용자 ID가 없거나 세션 조회가 실패하면 재조회/오류 화면이 나온다.',
        '4. 정시 시간창에서 GPS 출석을 요청한다. 지각 시간창에는 사유 제출을 주 CTA로 바꾼다. 일정 ID가 없거나 시간창 밖이거나 이미 확정된 상태에서는 제출을 막는다.',
        '5. 요청 후 승인 대기 카드 또는 최종 상태를 표시한다. 운영진은 출석 목록의 세션 상세에서 대기자별 승인/거절, 전체 승인/거절 및 사유 확인을 한다.',
        '6. 출석 링크는 활동 탭과 해당 세션 카드로 연결되며, 정시/지각의 미체크인 일정은 Live Activity로도 표시된다.',
      ],
      questions: ['GPS 출석 자동 판정과 운영진 수동 승인 각각의 기준·우선순위를 어떻게 정하는가?', '2단계 스터디 일정 연결 실패 후 취소 시 이미 생성된 일정의 정리 정책은 무엇인가?'],
      sources: ['UMCApp/Features/Home/Presentation/Sources/ViewModels/ScheduleRegistrationViewModel.swift:542', 'UMCApp/Features/Activity/Presentation/Sources/ViewModels/StudyScheduleRegistrationViewModel.swift:365', 'UMCApp/UMCApp/Sources/RootTab/RootTabView.swift:306', 'UMCApp/Features/Activity/Presentation/Sources/Components/Challenger/Attendance/ChallengerAttendanceView.swift:259', 'UMCApp/Features/Activity/Presentation/Sources/ViewModels/ChallengerAttendanceViewModel.swift:66', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorAttendanceDetailView.swift:403'],
    },
    {
      body: '운영진은 스터디 그룹과 주차 일정을 구성하고, 챌린저는 커리큘럼과 개인 워크북을 조회해 허용된 미션을 제출한다. 운영진은 제출 현황에서 개인 워크북과 피드백을 확인한다.',
      points: [
        '1. 활동 탭의 운영진 스터디 관리에서 그룹을 만들고 멤버·멘토를 배정한다. 그룹의 일정 등록은 권한·참여자·주차 목록을 모두 로드한 뒤 진행한다.',
        '2. 챌린저 스터디 화면은 커리큘럼 진행률과 주차별 미션을 표시한다. 등록 주차가 없거나 해당 기수에 조회 권한이 없으면 빈/안내 상태를 보여 준다.',
        '3. 내 워크북 목록에서 개인 워크북 ID가 있는 항목만 상세로 들어간다. 배포되지 않은 항목은 안내만 보인다.',
        '4. 상세의 미션 제출은 본인 소유, 미공결, 마감 전, 변경 중 아님, 지원 유형(LINK/MEMO/PLAIN) 조건을 통과해야 한다. 제출·수정·철회 결과는 상세와 목록을 새로 조회한다.',
        '5. 운영진 제출 현황에서도 개인 워크북 ID가 있는 항목을 상세 시트로 연다. ID가 없으면 워크북 미배포 알림을 띄우며, 피드백 작성은 담당 멘토 등 권한에 따라 제한한다.',
      ],
      questions: ['워크북 배포 시점과 미션 제출 마감 연장 권한은 누구에게 있는가?', '제출 철회 시 피드백 삭제와 동일 미션 재제출 금지가 기획 정책과 일치하는가?'],
      sources: ['UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorStudyManagementView.swift:82', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/StudyScheduleRegistrationView.swift:61', 'UMCApp/Features/Activity/Presentation/Sources/Views/Challenger/ChallengerStudyView.swift:49', 'UMCApp/Features/Activity/Presentation/Sources/Views/WorkbookView.swift:93', 'UMCApp/Features/Activity/Presentation/Sources/ViewModels/WorkbookViewModel.swift:97', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorStudyManagementView.swift:93'],
    },
    {
      body: '커뮤니티 탭에서 스레드를 만들면 목록에 반영되고, 참여자는 채팅방에서 실시간으로 대화한다. 방장/관리자는 스레드와 참여자 상태를 별도 동선에서 관리한다.',
      points: [
        '1. 스레드 목록에서 새 스레드를 누른다. 생성 폼의 필수값·초대 인원 조건이 맞을 때만 생성 CTA가 켜지고, 성공 시 목록에 새 행을 삽입한다.',
        '2. 목록의 스레드 행이나 `umc://thread/{id}` 링크로 채팅방에 들어간다. 채팅방은 헤더·메시지 로드와 실시간 구독을 시작하며 헤더가 없을 때는 전송을 잠근다.',
        '3. 메시지는 먼저 전송 중 상태로 보이고 서버 이벤트가 오면 확정된다. 실패한 메시지는 재시도할 수 있으며 사진은 업로드가 끝나 파일 ID를 얻은 뒤 전송한다.',
        '4. 대화 중 답장·멘션·반응, 본인 메시지 수정, 권한별 삭제/신고를 할 수 있다. 오래된 메시지는 화면 진입에 따라 추가로 불러온다.',
        '5. 멤버 목록에서 초대·강퇴·소유권 이전·퇴장/삭제를 처리한다. 참여가 끝나거나 추방되면 채팅방 대신 전용 안내를 띄운다.',
      ],
      questions: ['커뮤니티 신고 처리자와 제재/복구 기준은 무엇인가?', '스레드 공개 범위와 초대 한도, 보존 기간의 운영 정책을 확인해야 한다.'],
      sources: ['UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadListView.swift:78', 'UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadCreateView.swift:129', 'UMCApp/UMCApp/Sources/RootTab/RootTabView.swift:293', 'UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadRoomView.swift:199', 'UMCApp/Features/Community/Presentation/Sources/ViewModels/CommunityThreadRoomViewModel.swift:314', 'UMCApp/Features/Community/Presentation/Sources/ViewModels/ThreadMemberListViewModel.swift:112'],
    },
    {
      body: '지원자는 공개 프로젝트를 찾고 지원 폼을 작성·제출한다. 심사 권한이 있는 운영진은 지원자 목록이나 통합 수신함에서 응답을 열어 합격/불합격을 결정한다.',
      points: [
        '1. 마이페이지의 내 프로젝트에서 프로젝트 찾기로 이동한다. 공개 목록에서 상세를 열고, 서버 권한이 지원서 생성 가능으로 판정할 때만 지원 CTA가 나온다.',
        '2. 최초 작성은 지원 가능 매칭 차수를 고르고 질문에 답한다. 필수 답변 누락이나 앱이 지원하지 않는 파일·일정 질문 유형이 있으면 임시 저장과 제출이 막힌다.',
        '3. 임시 저장은 지원서 생성 후 답변 저장으로 이어진다. 제출은 저장 성공 후 별도 제출 API를 호출한다. 기존 지원서에서는 수정/철회 권한에 따라 버튼이 달라진다.',
        '4. 운영진은 프로젝트별 지원자 목록이나 전체 지원자 관리에서 상태별로 찾는다. 지원자 상세에 결정 권한이 있으면 확인 다이얼로그 후 합격·불합격을 처리하고 상태를 갱신한다.',
        '5. 프로젝트 상세의 검토 요청·지원 폼 편집·멤버 관리·소유권 양도·삭제는 프로젝트 상태와 개별 권한에 의해 별도 노출된다.',
      ],
      questions: ['모집 마감·정원 초과와 지원서 철회/재지원의 정책은 무엇인가?', '지원 결정 사유 입력 필수 여부와 결과 알림 방법을 확정해야 한다.'],
      sources: ['UMCApp/Features/Project/Presentation/Sources/Views/MyProjectsView.swift:68', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectDetailView.swift:124', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicationEditorView.swift:140', 'UMCApp/Features/Project/Presentation/Sources/ViewModels/ProjectApplicationEditorViewModel.swift:120', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicantsView.swift:45', 'UMCApp/Features/Project/Presentation/Sources/ViewModels/ProjectApplicationReviewViewModel.swift:64'],
    },
    {
      body: '마이페이지에서 내 명함을 조회하고 받은 명함을 보관한다. QR 스캔 또는 명함 링크는 수신·저장으로 연결되지만, 근거리 교환과 내 QR CTA는 현재 일반 마이페이지에서 숨겨져 있다.',
      points: [
        '1. 마이페이지가 내 명함을 로드한다. 프로필 정보 편집 후 내 명함이 갱신되며 로딩 실패 시 재시도할 수 있다.',
        '2. 받은 명함에서 명함첩을 열어 검색·상세를 본다. 명함첩의 스캔 CTA는 카메라 권한을 준비한 뒤 스캔을 시작하고, 거부 시 시스템 설정으로 안내한다.',
        '3. QR 스캔 결과는 명함 딥링크와 같은 수신 경로로 보내 조회·저장·완료 화면을 처리한다. 저장된 명함은 명함첩에서 다시 조회한다.',
        '4. 근거리 교환 구현은 상대 검색, 상대 선택 후 전송, 완료 화면으로 구성되며 권한 거부·세션 만료·전송/저장 실패를 분리해 복구한다.',
        '5. 현재 마이페이지의 내 명함에는 교환·QR CTA가 전달되지 않는다. 따라서 일반 사용자용 배포 흐름을 설명할 때 두 기능을 이미 공개된 것으로 간주하지 않는다.',
      ],
      questions: ['교환·QR 버튼의 공개 시점과 사전 권한 안내는 언제 확정할 것인가?', '명함 링크를 받은 사람의 저장 전 확인·동의 및 개인정보 보존 정책은 어떻게 운영하는가?'],
      sources: ['UMCApp/Features/MyPage/Presentation/Sources/Views/MyPageView.swift:141', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/ReceivedCardsView.swift:94', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/CardScanView.swift:70', 'UMCApp/UMCApp/Sources/RootTab/RootTabView.swift:300', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/CardExchangeView.swift:152', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/ExchangeCompletedView.swift:103'],
    },
  ],
}
