export default {
  id: 'chapter-05',
  number: '05',
  label: '핵심 장',
  title: '화면별 기능 명세',
  summary: '실제 화면을 기준으로 기능과 예외 상황을 빠짐없이 기록합니다.',
  topics: [
    '인증·온보딩',
    '홈',
    '공지',
    '활동: 출석·스터디·운영 기능',
    '커뮤니티',
    '프로젝트 지원·심사',
    '마이페이지·명함',
    '배지 등 부가 기능',
    '점검·업데이트 안내',
    'watchOS·Live Activity',
  ],
  note: {
    title: '화면군별 동작과 미확인 사항',
    body: '각 화면군의 진입 경로·행동·결과·예외를 코드 근거와 함께 정리하고, 확인이 필요한 정책은 PM 질문으로 남겼습니다.',
  },
  details: [
    {
      body: '앱 시작 시 인증 상태를 판정해 메인, 로그인, 가입 또는 승인 대기로 보낸다. 소셜 로그인과 이메일 로그인은 서로 다른 진입 화면을 공유한다.',
      points: [
        '부트스트랩은 인증 판정이 끝날 때까지 시작 화면을 보여 주며, 네트워크 타임아웃 때 재시도 화면으로 전환한다.',
        '로그인 화면은 카카오·Apple·Google·이메일을 제공한다. 이메일 화면에는 회원가입과 비밀번호 재설정 링크가 있고, 입력 조건이 충족될 때만 로그인 버튼을 누를 수 있다.',
        '이메일 가입은 학교·약관을 먼저 불러오고 이메일 중복 확인 결과를 표시한다. 가입 완료 후 승인 여부에 따라 메인 또는 승인 대기로 이동한다.',
        '소셜 가입 경로는 별도 SignUpView에서 추가 정보를 받는다. 비밀번호 재설정, 이메일 변경, 비밀번호 변경도 별도 화면으로 존재한다.',
      ],
      groups: [
        { title: '부트스트랩·로그인', points: ['승인된 세션은 메인, 미승인 세션은 승인 대기로 직행한다. 미로그인 상태에서만 로그인 선택지를 노출한다.', '인증 판정 실패는 무한 대기하지 않고 네트워크 안내와 재시도를 제공한다.'] },
        { title: '이메일 로그인·가입', points: ['이메일·비밀번호 입력이 유효해야 로그인 CTA가 켜지며 요청 중에는 스피너와 중복 탭 방지가 적용된다.', '이메일 중복 확인의 로딩·사용 가능·사용 불가·실패를 각각 표시하고 실패 때 재시도할 수 있다.'] },
        { title: '승인 대기·계정 복구', points: ['로그인/가입 후 미승인 프로필은 승인 대기 화면으로 분기한다.', '비밀번호 찾기와 계정 설정의 이메일·비밀번호 변경은 별도 화면으로 연결된다.'] },
        { title: '이메일·비밀번호 변경', points: ['계정 설정에서 이메일 또는 비밀번호 변경 화면을 연다.', '제출 성공을 확인한 뒤 화면을 닫으며 실패·입력 오류는 각 화면 안에서 안내한다.'] },
      ],
      questions: ['승인 대기 상태를 PM이 수동 해제하는 운영 절차와 기대 소요 시간은 무엇인가?', '소셜 가입과 이메일 가입의 필수 정보·약관이 동일해야 하는가?'],
      sources: ['UMCApp/Features/Auth/Presentation/Sources/Views/BootstrapView.swift:256', 'UMCApp/Features/Auth/Presentation/Sources/Views/LoginView.swift:57', 'UMCApp/Features/Auth/Presentation/Sources/Views/EmailLoginView.swift:165', 'UMCApp/Features/Auth/Presentation/Sources/Views/SignUpByIdPwView.swift:124', 'UMCApp/Features/Auth/Presentation/Sources/Views/ChangeEmailView.swift:49', 'UMCApp/Features/Auth/Presentation/Sources/Views/ChangePasswordView.swift:64', 'UMCApp/Features/Auth/Presentation/Sources/Views/ResetPasswordView.swift:50'],
    },
    {
      body: '홈은 프로필과 일정, 최근 공지를 한 화면에서 확인하는 진입점이다. 상단 알림 보관함과 일정·공지 카드는 각각 다음 화면으로 이어진다.',
      points: [
        '시즌 카드와 기수별 상벌점은 프로필 조회 결과를 쓴다. 프로필 실패 시 재시도 안내를 한 번 표시하고 상벌점 영역은 숨긴다.',
        '월별 캘린더에서 날짜를 고르면 해당 일정 카드가 나타난다. 일정이 없으면 빈 상태를, 분류 정보가 준비 중이면 자리 표시자를 보여 준다.',
        '일정 카드는 상세로 이동한다. 상세는 위치 지도 링크·출석 현황 진입을 제공하며 조회 실패 시 화면 안에서 재시도한다.',
        '최근 공지는 별도 로딩·오류 상태를 가지며 공지 탭 시 상세로 이동한다. 알림 보관함에서는 항목 삭제와 전체 삭제가 가능하다.',
        '새로고침은 프로필을 갱신하고, 상벌점 변경 신호를 받으면 캐시를 우회해 다시 조회한다.',
      ],
      groups: [
        { title: '홈 대시보드', points: ['시즌·상벌점·달력·선택 날짜 일정·최근 공지의 순서로 표시한다.', 'Apple Intelligence 비활성 사용자에게는 기기당 한 번 안내 시트를 띄울 수 있다.'] },
        { title: '일정 상세·등록', points: ['일정 상세에서 출석 현황과 지도 링크를 열 수 있다. 편집·삭제 액션은 화면의 액션 메뉴와 권한에 따른다.', '일정 등록 화면은 날짜·시간·태그·장소·참여자·출석 정책을 입력받고 권한 조회 실패와 제출 중 상태를 처리한다.'] },
        { title: '알림 보관함', points: ['저장된 알림이 없으면 빈 상태를 보여 주고, 항목 삭제 및 전체 삭제를 제공한다.'] },
      ],
      questions: ['알림 보관함의 보존 기간과 전체 삭제 복구 정책은 어떻게 운영하는가?', '홈 최근 공지 5건의 노출 우선순위가 운영 정책과 일치하는가?'],
      sources: ['UMCApp/Features/Home/Presentation/Sources/Views/HomeView.swift:82', 'UMCApp/Features/Home/Presentation/Sources/Views/HomeView.swift:133', 'UMCApp/Features/Home/Presentation/Sources/Views/HomeView.swift:238', 'UMCApp/Features/Home/Presentation/Sources/Views/ScheduleDetailView.swift:176', 'UMCApp/Features/Home/Presentation/Sources/Views/NoticeAlarmView.swift:41'],
    },
    {
      body: '공지 탭은 수신 대상에 맞는 공지를 검색·필터링해 보여 주고, 상세 진입 시 읽음을 기록한다. 작성 권한이 있는 운영진은 공지를 만들고 열람 현황과 재알림을 관리한다.',
      points: [
        '공지 목록은 제목·내용 검색을 1초 디바운스로 실행하고, 목록 하단 진입 시 다음 페이지를 불러온다. 로딩·빈 결과·권한 없음·조회 실패를 구분한다.',
        '상세는 본문·이미지·링크·투표를 표시한다. 진입 시 읽음 API와 상세/권한/통계를 조회하되 읽음 처리 실패만으로 상세 진입을 막지 않는다.',
        '운영진 공지 작성 버튼은 선택 탭과 역할의 쓰기 권한이 맞을 때만 보인다. 작성 폼은 제목·본문 필수, 운영진 공지는 기수 선택도 필수다.',
        '수신 확인 현황은 확인·미확인 목록과 필터를 제공한다. 미확인자 개별 스와이프 재알림과 전체 미확인자 재알림을 실행한다.',
        '공지 수정·삭제와 AI 문장 개선/요약은 해당 권한과 기기 지원 여부에 따라 노출된다.',
      ],
      groups: [
        { title: '일반 공지 목록·상세', points: ['공지 탭과 홈 최근 공지에서 상세로 들어간다.', '상세 진입 시 읽음 처리 후 통계를 새로 불러오며, 상세 조회 실패에는 재시도 화면을 보여 준다.'] },
        { title: '운영진 공지·편집기', points: ['중앙·학교 코어·학교 파트장 탭에서 각 역할의 쓰기 권한을 검사한 뒤 작성 버튼을 보여 준다.', '대상 선택, 리치 텍스트, 이미지, 링크, 투표를 구성하고 필수 항목 누락 시 제출을 막는다.'] },
        { title: '열람 현황·재알림', points: ['확인·미확인 현황을 분리해 표시하고 전체/지부/학교 필터를 적용한다.', '미확인자 한 명 또는 페이지를 순회해 수집한 전체 대상자에게 재알림을 보낸다.'] },
      ],
      questions: ['재알림 발송 간격·횟수 제한 및 운영진 권한 범위는 어떤 정책으로 정할 것인가?', '공지의 읽음과 명시적 수신 확인을 동일한 행동으로 볼 것인가? 현재 iOS 상세는 진입 시 읽음 처리한다.'],
      sources: ['UMCApp/Features/Notice/Presentation/Sources/Views/NoticeView.swift:225', 'UMCApp/Features/Notice/Presentation/Sources/Views/NoticeDetail/NoticeDetailView.swift:402', 'UMCApp/Features/Notice/Presentation/Sources/Views/StaffNotice/StaffNoticeView.swift:242', 'UMCApp/Features/Notice/Presentation/Sources/ViewModels/NoticeEditor/NoticeEditorViewModel.swift:242', 'UMCApp/Features/Notice/Presentation/Sources/Views/NoticeDetail/NoticeReadStatusSheet.swift:180'],
    },
    {
      body: '활동 탭은 사용자 역할에 따라 챌린저의 출석·스터디·멤버 화면과 운영진의 출석·스터디·멤버 관리 화면을 분리한다. 홈 일정 상세와 출석 딥링크도 이 탭으로 연결된다.',
      points: [
        '챌린저 출석은 세션·사용자 ID가 모두 준비되어야 열린다. 정시 구간에는 GPS 출석, 지각 구간에는 사유 제출을 기본 행동으로 제시하고 확정 상태에서는 버튼을 비활성화한다.',
        '운영진 출석 목록은 필터·세션 상세를 제공한다. 상세에서는 승인 대기 참여자별 승인/거절 및 전체 승인/거절을 할 수 있고 처리 중인 행은 잠긴다.',
        '챌린저 스터디는 커리큘럼 진행률·주차 미션과 내 워크북/미션 제출 진입을 제공한다. 커리큘럼 미등록은 정상 빈 상태, 일반 조회 실패는 재시도로 구분한다.',
        '운영진 스터디는 그룹 관리와 제출 현황을 나눈다. 그룹 생성·멤버/멘토 추가·일정 등록은 권한 확인 후 열고, 워크북 미배포 항목은 안내를 보여 준다.',
        '운영진 멤버 관리와 챌린저 멤버 목록·검색은 별도 화면이며, 운영진은 멤버 상세에서 상벌점 등 관리를 진행한다.',
      ],
      groups: [
        { title: '챌린저 출석', points: ['세션 목록과 개별 출석 카드에서 GPS 출석 또는 지각/공결 사유 제출을 선택한다.', '사용자 ID 없음·세션 조회 실패·일정 ID 없음·시간창 종료는 제출을 막거나 재조회 안내로 분기한다.'] },
        { title: '운영진 출석', points: ['출석 관리 목록에서 일정 필터 후 세션 상세에 진입한다.', '상세에서 참여자 상태별 필터, 개별 승인/거절, 전체 승인/거절, 사유 확인과 장소 관련 행동을 제공한다.'] },
        { title: '챌린저 스터디·워크북', points: ['진행률과 주차별 미션을 확인하고 내 워크북·미션 제출 화면으로 이동한다.', '미등록·기수 조회 불가·일반 실패는 서로 다른 안내를 보여 준다.'] },
        { title: '운영진 스터디·멤버', points: ['그룹 생성·수정·멤버/멘토 추가 후 일정 등록 화면으로 이동한다. 등록은 권한·참여자·주차 정보를 함께 확인한다.', '제출 현황 항목에 개인 워크북 ID가 없으면 미배포 안내가 나온다. 멤버 관리는 별도 화면으로 분리된다.'] },
        { title: '챌린저 멤버 목록·상세', points: ['파트별 멤버 목록을 검색하고 멤버 행에서 상세 시트를 연다.', '초기 로딩·빈 목록·검색 결과 없음·조회 실패를 분리하며 상세를 가져오는 동안 화면 중앙에 진행 상태를 띄운다.'] },
        { title: '운영진 멤버 관리·상세', points: ['파트별 목록 검색과 멤버 상세 시트를 제공하며, 상세에서 권한 있는 상벌점 등 운영 작업으로 이어진다.', '로딩·빈 목록·검색 결과 없음·조회 실패 시에는 각각 다른 상태를 표시하고 재조회할 수 있다.'] },
      ],
      questions: ['GPS 허용 반경·정시/지각 경계와 사유 승인 기준의 최종 운영 정책은 무엇인가?', '제출 현황의 서버 연동 범위와 워크북 미배포 때 운영진 대응 절차를 확정해야 하는가?'],
      sources: ['UMCApp/Features/Activity/Presentation/Sources/Views/ActivityView.swift:190', 'UMCApp/Features/Activity/Presentation/Sources/Components/Challenger/Attendance/ChallengerAttendanceView.swift:259', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorAttendanceDetailView.swift:403', 'UMCApp/Features/Activity/Presentation/Sources/Views/Challenger/ChallengerStudyView.swift:49', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorStudyManagementView.swift:82', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/StudyScheduleRegistrationView.swift:61', 'UMCApp/Features/Activity/Presentation/Sources/Views/Challenger/ChallengerMemberListView.swift:55', 'UMCApp/Features/Activity/Presentation/Sources/Views/Operator/OperatorMemberManagementView.swift:58'],
    },
    {
      body: '커뮤니티는 스레드 목록·생성·채팅방·편집·멤버 관리로 이어진다. 메시지는 실시간 연결로 갱신하고 공지 링크 카드에서는 공지 상세로 이동한다.',
      points: [
        '목록은 고정/일반 스레드, 검색·다음 페이지, 생성 버튼을 제공하며 로딩·빈 목록·실패 상태를 분리한다.',
        '스레드 생성은 제목·설명·초대 대상과 분류 입력을 받고 제출 가능 조건을 만족할 때만 생성 버튼이 켜진다. 성공하면 목록에 즉시 반영된다.',
        '채팅방은 메시지 목록·이전 메시지 로딩, 텍스트·사진 전송, 답장 인용, 멘션, 반응, 복사·수정·신고·삭제, AI 요약을 제공한다.',
        '방장/관리자 권한에 따라 스레드 정보 변경·초대·강퇴·소유권 이전·삭제가 달라진다. 퇴장/추방 시 기존 방 본체를 걷어 내고 전용 안내로 바꾼다.',
        '방 헤더를 받기 전 전송창을 비활성화하고, 전송 실패한 메시지는 다시 보내기를 제공한다.',
      ],
      groups: [
        { title: '스레드 목록·생성·편집', points: ['탭 진입 후 목록과 실시간 이벤트를 읽는다. 새 스레드 버튼에서 생성 폼으로 이동한다.', '생성/편집 성공과 삭제는 목록 상태에 즉시 반영된다.'] },
        { title: '채팅방·멤버 관리', points: ['방 입장 후 헤더·메시지를 로드하고 실시간 이벤트를 구독한다.', '초대·멤버 목록·소유권 이전·퇴장/추방과 메시지 신고 등은 역할별 메뉴에서 접근한다.'] },
      ],
      questions: ['신고 접수 후 실제 운영진 처리·제재 SLA는 무엇인가?', 'AI 요약 제공 대상과 기기 지원 실패 시 대체 경험을 어떻게 정의할 것인가?'],
      sources: ['UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadListView.swift:78', 'UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadCreateView.swift:129', 'UMCApp/Features/Community/Presentation/Sources/Views/CommunityThreadRoomView.swift:222', 'UMCApp/Features/Community/Presentation/Sources/ViewModels/CommunityThreadRoomViewModel.swift:314', 'UMCApp/Features/Community/Presentation/Sources/ViewModels/ThreadMemberListViewModel.swift:112'],
    },
    {
      body: '프로젝트는 마이페이지의 내 프로젝트에서 공개 목록·상세·지원서 작성으로 이어진다. 프로젝트 운영 권한이 있는 사람에게만 관리와 심사 행동이 노출된다.',
      points: [
        '내 프로젝트는 운영 가능 프로젝트, 지원 내역, 프로젝트 찾기와 권한 있는 운영진의 프로젝트 운영 진입을 한곳에 모은다.',
        '공개 프로젝트 목록은 빈·로딩·오류·다음 페이지를 처리한다. 상세는 PM·상태·파트별 정원·멤버를 보여 주고 권한별로 지원/지원자 관리/정보 수정/검토 요청을 분기한다.',
        '지원서는 차수와 질문별 응답을 받는다. 임시 저장·제출·철회가 상태/권한에 따라 노출되고 파일·일정·알 수 없는 질문 유형은 현재 앱에서 작성할 수 없다.',
        '운영진 지원자 목록은 상태 필터와 빈·오류 상태를 제공한다. 지원자 상세에서는 결정 권한이 있을 때 합격/불합격을 확인 후 처리한다.',
        '프로젝트 운영 화면에는 공개·정원·매칭 차수·통계 관련 관리 동선이 있고, 상세 권한에 따라 팀원/보조 PM 관리·소유권 양도·지원 폼 편집도 제공한다.',
      ],
      groups: [
        { title: '탐색·상세', points: ['마이페이지의 내 프로젝트에서 프로젝트 찾기를 열고 공개 목록 행에서 상세로 간다.', '상세의 각 관리 버튼은 서버 권한과 프로젝트 상태가 허용할 때만 보인다.'] },
        { title: '지원·심사', points: ['지원 폼에서 차수와 질문 응답을 작성해 저장 또는 제출한다.', '운영진은 지원자 목록/통합 수신함에서 지원서를 열고 결정 권한이 있을 때 합격·불합격한다.'] },
        { title: '프로젝트 운영', points: ['초안 생성, 정보 수정, 멤버·보조 PM 관리, 소유권 이전, 검토 요청, 공개·정원·매칭 운영 화면이 구분되어 있다.'] },
        { title: '지원 폼·전체 지원자 관리', points: ['지원 폼 편집은 로딩·실패·작성 상태를 분리하고 권한 있는 PM에게 노출된다.', '전체 지원자 수신함은 프로젝트별 지원자를 묶어 보여 주며 빈 목록과 조회 실패에는 안내·재시도를 제공한다.'] },
      ],
      questions: ['지원 차수 종료·정원 마감·지원 취소 시점의 공통 정책을 확정했는가?', '지원 폼의 파일·일정 질문 유형을 허용할지, 허용한다면 iOS 구현 일정은 언제인가?'],
      sources: ['UMCApp/Features/Project/Presentation/Sources/Views/MyProjectsView.swift:53', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectBrowseView.swift:40', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectDetailView.swift:105', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicationEditorView.swift:87', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicantsView.swift:45', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicationReviewView.swift:114', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectAdminView.swift:47', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicationFormEditorView.swift:35', 'UMCApp/Features/Project/Presentation/Sources/Views/ProjectApplicationInboxView.swift:30'],
    },
    {
      body: '마이페이지는 개인 프로필·명함·활동 기록·프로젝트·게시물·설정으로 갈라지는 허브다. 명함첩에서 받은 명함을 검색·조회하고 QR 스캔으로 추가할 수 있다.',
      points: [
        '마이페이지는 내 명함, 받은 명함, 정보 편집, 스터디·활동·수료증·프로젝트, 작성/댓글/스크랩 게시물, 설정으로 연결한다.',
        '명함 로딩 실패는 재시도를 제공한다. 현재 iOS 코드에서 마이페이지 명함 카드의 근거리 교환·QR 버튼은 숨겨져 있고, 받은 명함·스캔 경로는 노출된다.',
        '받은 명함은 검색·빈 상태·오류 재시도를 제공하며 상세에서 연락 정보 확인, 메모/삭제를 처리한다. 스캔 권한 거부는 설정 이동, 미지원 기기는 별도 안내로 분기한다.',
        'QR 생성·공유·이미지 저장, 근거리 상대 검색·교환·완료 화면의 구현은 코드에 있으나 일반 마이페이지 경로에서는 진입 버튼이 숨겨져 있다.',
        '설정은 계정 연결/해제와 로그아웃 등의 작업을, 수료증 목록은 발급 가능 기수 및 다운로드/미발급·만료·철회 상태를 보여 준다.',
      ],
      groups: [
        { title: '프로필·활동·설정', points: ['명함 카드와 활동 통계, 내 스터디·프로젝트·게시물·수료증 진입을 제공한다.', '설정에서 계정 연동과 세션 종료를 처리하며 계정 변경 화면은 별도 라우트다.'] },
        { title: '활동 기록·게시물', points: ['활동 기록은 내역이 없을 때 빈 상태를, 있을 때 항목별 목록을 표시한다.', '작성 글·댓글·스크랩 목록은 상단 종류 전환, 다음 페이지 로딩, 빈 결과, 실패 재시도를 처리한다.'] },
        { title: '명함첩·QR 스캔', points: ['받은 명함 행에서 명함첩을 열고 검색/상세로 이동한다. 명함첩의 스캔 버튼은 카메라 권한에 따라 스캐너 또는 권한 안내를 보여 준다.', '인식한 링크는 딥링크와 같은 수신·저장 경로로 처리한다.'] },
        { title: '숨겨진 교환·QR 화면', points: ['명함 QR의 공유/저장과 근거리 교환 화면은 구현돼 있다.', '마이페이지의 기본 명함 카드에서 해당 두 CTA는 현재 전달되지 않아 보이지 않는다.'] },
      ],
      questions: ['명함 교환·QR CTA를 재노출할 출시 조건과 QA 기준은 무엇인가?', '받은 명함의 보관/삭제·개인정보 보존 정책은 확정됐는가?'],
      sources: ['UMCApp/Features/MyPage/Presentation/Sources/Views/MyPageView.swift:65', 'UMCApp/Features/MyPage/Presentation/Sources/Views/MyPageView.swift:141', 'UMCApp/Features/MyPage/Presentation/Sources/Views/MyActivityLogsView.swift:40', 'UMCApp/Features/MyPage/Presentation/Sources/Views/MyActivePostsView.swift:90', 'UMCApp/Features/MyPage/Presentation/Sources/Views/MyPageSettingsView.swift:60', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/ReceivedCardsView.swift:76', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/CardScanView.swift:80', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/CardQRView.swift:187', 'UMCApp/Features/BusinessCard/Presentation/Sources/Views/CardExchangeView.swift:152'],
    },
    {
      body: '배지 모듈은 현재 실제 사용자 기능 화면으로 연결된 명세가 없다. 수료증과 상벌점은 각각 마이페이지와 홈·활동에 구현되어 있으므로 배지 기능과 구분해야 한다.',
      points: [
        'BadgeFeatureView는 현재 “Badge Feature” 텍스트만 렌더링하는 자리 표시자다. 획득·목록·상세·공유 동작을 명세된 기능처럼 적지 않는다.',
        '수료증 목록은 발급 가능 기수를 보여 주고 발급·미리보기/다운로드를 제공한다. 발급 취소/만료된 항목은 다운로드가 제한된다.',
        '홈의 기수별 상벌점 카드와 운영진 멤버 관리의 상벌점 동선은 배지와 별개의 구현이다.',
      ],
      groups: [
        { title: '배지', points: ['사용자용 배지 여정은 현재 자리 표시자 수준이다.'] },
        { title: '수료증·상벌점', points: ['수료증 발급/다운로드는 마이페이지에서 접근한다.', '상벌점은 홈 카드와 운영진 멤버 관리에서 확인한다.'] },
      ],
      questions: ['배지를 실제 출시 범위에 포함할 것인가? 획득 규칙·노출 위치·운영 소유자를 확정해야 한다.'],
      sources: ['UMCApp/Features/Badge/Presentation/Sources/BadgeFeatureView.swift:10', 'UMCApp/Features/MyPage/Presentation/Sources/Views/CertificateListView.swift:68', 'UMCApp/Features/Home/Presentation/Sources/Views/HomeView.swift:160'],
    },
    {
      body: '앱은 시작과 활성 복귀 때 원격 운영 상태를 다시 확인한다. 점검 중 또는 최소 지원 버전 미달이면 전체 화면 안내를 띄운다.',
      points: [
        '점검 안내는 원격 설정의 제목·메시지를 사용하고, 강제 업데이트 안내는 앱스토어 이동 버튼을 제공한다.',
        '안내 화면은 스와이프로 닫지 못한다. 점검/업데이트 판단이 해제되기 전에는 기본 사용자 흐름으로 돌아갈 수 없다.',
        '원격 설정 점검이 강제 업데이트보다 우선하며, 업데이트 판정은 원격 최소 버전과 앱스토어 버전을 함께 확인한다.',
        '화면별 정보 안내는 별도 경고로 노출할 수 있다. 원격 설정이 실패할 때의 기본값·배포 운영 절차는 PM 정책 확인이 필요하다.',
      ],
      groups: [
        { title: '점검·강제 업데이트', points: ['시작과 앱 활성 복귀에서 정책을 확인해 차단형 전체 화면으로 띄운다.', '강제 업데이트 CTA는 앱스토어로 이동하며 점검 화면에는 우회 CTA가 없다.'] },
      ],
      questions: ['점검 시작/종료 시각과 긴급 해제 책임자, 원격 설정 게시 절차를 누가 관리하는가?', '앱스토어 심사 지연 중 최소 지원 버전 상향을 금지하는 운영 규칙이 있는가?'],
      sources: ['UMCApp/UMCApp/Sources/UMCAppApp.swift:99', 'UMCApp/Features/Maintenance/Presentation/Sources/Views/MaintenanceView.swift:68', 'UMCApp/Features/Maintenance/Presentation/Sources/ViewModels/MaintenanceViewModel.swift:72', 'UMCApp/Features/Maintenance/Domain/Sources/UseCases/Implementations/CheckForceUpdateUseCase.swift:43'],
    },
    {
      body: '워치는 오늘 세션·The Ping·출석 결과를 짧은 동선으로 보여 준다. iPhone의 출석 시간창은 잠금 화면 Live Activity에도 반영된다.',
      points: [
        '워치 홈에서 세션 카드와 The Ping 카드로 각각 출석·공지 목록에 들어간다. 세션 데이터가 없거나 iPhone과 연결이 끊기면 빈 상태/폴백 안내를 보여 준다.',
        '워치 출석 목록은 로딩·빈·오류를 나누고, 세션 상세에서 출석 동작을 요청한 뒤 승인 대기/출석/지각/공결/결석 결과를 보여 준다.',
        '워치 Ping 목록은 긴급성과 읽지 않음을 별도 신호로 표시한다. 상세의 ‘확인했습니다’는 iPhone에 읽음 확인을 전송한다.',
        '출석 Live Activity는 출석 정책이 있고 미체크인 상태인 일정이 정시·지각 시간창에 들어왔을 때 생성한다. 출석 요청/마감 시 종료하며 시스템 설정에서 Live Activity가 꺼져 있으면 조용히 건너뛴다.',
        '워치 라우트에서 iPhone 동기화 전 일정 ID를 찾지 못하면 플레이스홀더로 이동한다. 워치의 일부 폴백 화면은 아직 디버그 진입만 존재한다.',
      ],
      groups: [
        { title: 'watchOS 홈·출석', points: ['홈 세션 카드에서 출석 목록/세션으로 이동한다.', '워치가 일정을 아직 받지 못했으면 플레이스홀더, iPhone 연결이 끊겼으면 연결 안내를 보여 준다.'] },
        { title: 'watchOS The Ping', points: ['홈 Ping 카드에서 목록과 상세로 이동하고 확인 CTA로 iPhone에 읽음 이벤트를 보낸다.'] },
        { title: 'iOS Live Activity', points: ['정시·지각 구간의 미체크인 일정만 대상으로 띄우고 시간 경계에 갱신한다.', '출석 요청 시 즉시 종료, 마감 시 닫힘 상태를 잠시 표시한다.'] },
      ],
      questions: ['워치 단독 연결 해제 상태에서 출석·공지 확인의 허용 범위와 재전송 SLA는 무엇인가?', 'Live Activity 문구·노출 우선순위가 다수 동시 세션에서 어떻게 적용돼야 하는가?'],
      sources: ['UMCApp/UMCWatchApp/Sources/Home/HomeGlanceView.swift:53', 'UMCApp/UMCWatchApp/Sources/Routing/WatchRootView.swift:47', 'UMCApp/UMCWatchApp/Sources/Ping/PingDetailView.swift:96', 'UMCApp/UMCWatchApp/Sources/Attendance/WatchAttendanceListView.swift:37', 'UMCApp/UMCApp/Sources/LiveActivity/AttendanceLiveActivityCoordinator.swift:113'],
    },
  ],
}
